### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by GillesD** [njoosse/python-runner#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [python-runner](https://github.com/njoosse/python-runner) package 1.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /private/var/folders/0l/gd_szmhd6pg8393lf56hvxlw0000gn/T/AppTranslocation/B70FACC3-11EB-43EA-BFC4-C4D19FB33173/d/Atom.app/Contents/Resources/app.asar/node_modules/graceful-fs/polyfills.js:21

Error: ENOENT: no such file or directory, uv_chdir
    at process.chdir (/app.asar/node_modules/graceful-fs/polyfills.js:21:9)
    at generateCommand (/packages/python-runner/lib/python-runner.js:64:10)
    at executePy (/packages/python-runner/lib/python-runner.js:82:12)
    at HTMLElement.pythonRunnerExecutePy (/packages/python-runner/lib/python-runner.js:119:38)
    at CommandRegistry.handleCommandEvent (/private/var/folders/0l/gd_szmhd6pg8393lf56hvxlw0000gn/T/AppTranslocation/F27A185B-7FAE-4324-A904-9DD68323C368/d/Atom-2.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/private/var/folders/0l/gd_szmhd6pg8393lf56hvxlw0000gn/T/AppTranslocation/F27A185B-7FAE-4324-A904-9DD68323C368/d/Atom-2.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/private/var/folders/0l/gd_szmhd6pg8393lf56hvxlw0000gn/T/AppTranslocation/F27A185B-7FAE-4324-A904-9DD68323C368/d/Atom-2.app/Contents/Resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/private/var/folders/0l/gd_szmhd6pg8393lf56hvxlw0000gn/T/AppTranslocation/F27A185B-7FAE-4324-A904-9DD68323C368/d/Atom-2.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:09.6.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-light-ui)
     -0:32.8.0 python-runner:executePy (input.hidden-input)
```

### Non-Core Packages

```
atom-hugo 0.1.1 
atom-python-run 0.9.6 
hugofy 2.0.0 
language-hugo 0.4.0 
nuclide undefined 
python-runner 1.1.0 
```

**Comment by PNRYates** [comment]
i have this problem as well
