### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by AhmedRamadanAhmed** [njoosse/python-runner#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Ubuntu 18.04.1
**Thrown From**: [python-runner](https://github.com/njoosse/python-runner) package 1.2.0

### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at exports.spawn (child_process.js:508:38)
    at Object.exports.execFile (child_process.js:224:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
    at exports.exec (child_process.js:154:18)
    at ELECTRON_ASAR.js:728:23
    at shellExec (/packages/python-runner/lib/python-runner.js:103:2)
    at executePy (/packages/python-runner/lib/python-runner.js:96:2)
    at HTMLElement.pythonRunnerExecutePy (/packages/python-runner/lib/python-runner.js:133:38)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1355:25)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:318:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:22.2.0 build:toggle-panel (input.hidden-input)
 10x -0:56.3.0 core:backspace (input.hidden-input)
     -0:55.5.0 intentions:highlight (input.hidden-input)
     -0:55.4.0 core:select-all (input.hidden-input)
     -0:55.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:51.8.0 editor:newline (input.hidden-input)
     -0:51.2.0 core:backspace (input.hidden-input)
     -0:50.3.0 core:move-right (input.hidden-input)
     -0:50 editor:newline (input.hidden-input)
     -0:44.6.0 core:move-right (input.hidden-input)
     -0:43.7.0 core:move-left (input.hidden-input)
  2x -0:43.4.0 core:backspace (input.hidden-input)
     -0:42 editor:newline (input.hidden-input)
     -0:41.5.0 core:backspace (input.hidden-input)
     -0:33.2.0 atom-python-test:run-all-project-tests (div.highlights)
     -0:21.9.0 python-runner:executePy (div.highlights)
```

### Non-Core Packages

```
atom-eclipse-syntax 0.0.6 
atom-python-run 0.9.7 
atom-python-test 0.9.0 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.10.12 
autocomplete-python-jedi 1.10.3-0 
build 0.70.0 
build-python 0.9.3 
busy-signal 1.4.3 
ide-python 1.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.7.1 
python-debugger 0.2.0 
python-indent 1.1.6 
python-runner 1.2.0 
python-tools 0.6.9 
```

**Comment by njoosse** [comment]
Should be addressed in v 1.2.1
