### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by PPBrus** [njoosse/python-runner#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Microsoft Windows 10 Education
**Thrown From**: [python-runner](https://github.com/njoosse/python-runner) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At C:\Users\te16sb1\.atom\packages\python-runner\lib\python-runner.js:44

TypeError: Cannot read property 'endsWith' of undefined
    at getFilePath (/packages/python-runner/lib/python-runner.js:44:15)
    at generateCommand (/packages/python-runner/lib/python-runner.js:57:17)
    at executePy (/packages/python-runner/lib/python-runner.js:96:12)
    at HTMLElement.pythonRunnerExecutePy (/packages/python-runner/lib/python-runner.js:133:38)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:349858)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1231210)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:1227344)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.33.0/resources/app/static/<embedded>:11:285037)
```

### Commands

```
     -6:57.4.0 core:paste (input.hidden-input)
  2x -6:47.6.0 core:backspace (input.hidden-input)
     -6:44.7.0 editor:newline (input.hidden-input)
  5x -6:44 core:backspace (input.hidden-input)
     -5:47.6.0 Python run: run-f5 (input.hidden-input)
     -2:16.5.0 core:confirm (input.hidden-input)
     -1:03.0 editor:newline (input.hidden-input)
     -1:01.9.0 Python run: run-f5 (input.hidden-input)
  2x -0:18.2.0 python-runner:executePy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-python-run 0.9.7 
autocomplete-python 1.11.0 
busy-signal 1.4.3 
file-icons 2.1.26 
intentions 1.1.5 
isotope-ui 2.8.5 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
python-runner 1.2.0 
python-tools 0.6.9 
slack-ui 0.8.0 
teletype 0.13.3 
```

**Comment by njoosse** [comment]
Should be addressed in v 1.2.1
