### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chdir '/' -> ''

### ISSUE THREAD

**Issue by zjxjohnxtlxb** [njoosse/python-runner#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.7
**Thrown From**: [python-runner](https://github.com/njoosse/python-runner) package 1.2.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, chdir '/' -> ''

```
At internal/process/main_thread_only.js:25

Error: ENOENT: no such file or directory, chdir '/' -> ''
    at process.chdir (internal/process/main_thread_only.js:25:20)
    at process.chdir (/app.asar/node_modules/graceful-fs/polyfills.js:20:9)
    at generateCommand (/packages/python-runner/lib/python-runner.js:69:10)
    at executePy (/packages/python-runner/lib/python-runner.js:102:12)
    at HTMLElement.pythonRunnerExecutePy (/packages/python-runner/lib/python-runner.js:143:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1231083)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1227217)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -5:10.7.0 script:run (input.hidden-input)
  7x -5:07.6.0 core:backspace (input.hidden-input)
 11x -5:05.3.0 core:undo (input.hidden-input)
     -4:59.6.0 script:run (input.hidden-input)
  2x -4:19.9.0 core:undo (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
 10x -4:17.9.0 core:redo (input.hidden-input)
  2x -4:11.6.0 script:run (input.hidden-input)
 10x -4:01.4.0 core:undo (input.hidden-input)
     -3:56.6.0 core:redo (input.hidden-input)
     -3:54.7.0 script:run (input.hidden-input)
     -3:46 core:undo (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -3:44.1.0 script:run (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
  2x -3:42.9.0 core:undo (div.am-panel.tool-panel.panel-bottom.native-key-bindings.script-view)
     -3:40.4.0 core:redo (input.hidden-input)
     -1:58.7.0 core:save (input.hidden-input)
     -0:08.3.0 python-runner:executePy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
color-picker 2.3.0 
docblock-python 0.19.0 
docblockr 0.13.7 
intentions 1.1.5 
linter 3.1.1 
linter-ui-default 2.1.2 
minimap 4.29.9 
python-runner 1.2.1 
teletype 0.13.4 
```

**Comment by MysticMia** [comment]
Can confirm with packages:
```
atom-beautify 0.33.4
minimap 4.38.2
python runner 1.3.0
script 3.26.0

```
